// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUtZm6ipnMk_7sLGx79iShOcZx5UNZD_k',
    appId: '1:1098508872113:web:e0bc7e4b94c994f3af3590',
    messagingSenderId: '1098508872113',
    projectId: 'flutterfix-713e8',
    authDomain: 'flutterfix-713e8.firebaseapp.com',
    storageBucket: 'flutterfix-713e8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv0rjnrQ_-e9zNgFCF9du_TmJWbQL7XmQ',
    appId: '1:1098508872113:android:b3665e84e5b42ffaaf3590',
    messagingSenderId: '1098508872113',
    projectId: 'flutterfix-713e8',
    storageBucket: 'flutterfix-713e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARtu6c8E_JVPJiC-6kl19IS62hHznHFuE',
    appId: '1:1098508872113:ios:b93e5545dc146843af3590',
    messagingSenderId: '1098508872113',
    projectId: 'flutterfix-713e8',
    storageBucket: 'flutterfix-713e8.firebasestorage.app',
    iosBundleId: 'com.example.pretestfix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARtu6c8E_JVPJiC-6kl19IS62hHznHFuE',
    appId: '1:1098508872113:ios:b93e5545dc146843af3590',
    messagingSenderId: '1098508872113',
    projectId: 'flutterfix-713e8',
    storageBucket: 'flutterfix-713e8.firebasestorage.app',
    iosBundleId: 'com.example.pretestfix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUtZm6ipnMk_7sLGx79iShOcZx5UNZD_k',
    appId: '1:1098508872113:web:528ed7ccec320586af3590',
    messagingSenderId: '1098508872113',
    projectId: 'flutterfix-713e8',
    authDomain: 'flutterfix-713e8.firebaseapp.com',
    storageBucket: 'flutterfix-713e8.firebasestorage.app',
  );
}
